apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "octoprint.fullname" . }}
  labels:
    {{- include "octoprint.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "octoprint.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "octoprint.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "octoprint.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ printf "%s:%s" .Values.image.repository (.Values.image.tag | default (include "octoprint.version" .)) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: octoprint
              containerPort: 5000
              protocol: TCP
          env:
            - name: SOCAT_DEV
              value: {{ .Values.socat.dev | default (printf "/dev/tty-%s" .Release.Name) | quote }}
            - name: SOCAT_TARGET
              value: {{ required "a value is required for socat target" .Values.socat.target | quote }}
          volumeMounts:
          - mountPath: /home/octoprint
            name: octoprint
            subPath: home
          - mountPath: /opt/octoprint/venv/lib/python3.9/site-packages
            name: octoprint
            subPath: packages
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: octoprint
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.existingClaim | default .Values.pvc.name | default (include "octoprint.pvcname" .) }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
