apiVersion: v1
kind: Service
metadata:
  name: {{ include "octoprint.fullname" . }}
  labels:
    {{- include "octoprint.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: octoprint
      protocol: TCP
      name: octoprint
  selector:
    {{- include "octoprint.selectorLabels" . | nindent 4 }}
